name: Imtiaz Willems
favicon: null
layout_spectrum: 0.56416
typography_spectrum: 0.333
title: ELECTRONIC MUSIC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: ' '
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeedf2'
    - '#191a2c'
    - '#a9a4aa'
    - '#9e2b0e'
    - '#e16e2f'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
