name: Imtiaz Willems
favicon: null
layout_spectrum: 0.99511
typography_spectrum: 0.333
title: ELECTRONIC MUSIC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: ' '
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1efd7'
    - '#252525'
    - '#acbcb5'
    - '#67675d'
    - '#86928d'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0
purpose: []
