name: Imtiaz Willems
favicon: null
layout_spectrum: 0
typography_spectrum: 0.30264
title: ADAM PHASE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: ' '
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efeee9'
    - '#d4d0c6'
    - '#2f5166'
    - '#7e9097'
    - '#0f2943'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
